#!/bin/bash

DATA_DIR=$HOME/.pomodoro
RING=$DATA_DIR/ring.mp3
trap exit_script TERM

function exit_script()
{
	echo "Exiting"
	notify-send "Exiting pomodor"
	exit 0
}

function notify()
{
	urgency=$1
	text=$2
	notify-send -u $urgency "$text"
}

time=$1
pausetime=$2

if [ -z "$time" ]
then
	time=25
fi
if [ -z "$pausetime" ]
then
	pausetime=5
fi

timeinc=`expr $time + 1`
for i in `seq 1 $time`
do
	left=`expr $timeinc - $i`	
	notify normal "$left mn left... keep going!"
	sleep 60 & # This trick is needed so that trap is immediatly executed when receiving SIGTERM
	wait

done
notify critical "DING ! Take a break !"
test -f $RING && mplayer -really-quiet $RING >& /dev/null
sleep `expr $pausetime \* 60`
notify critical "Break finished... go back to work"
test -f $RING && mplayer -really-quiet $RING >& /dev/null
